<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in with email_login</name>
   <tag></tag>
   <elementGuidId>8101d1dc-d6b5-4c0c-b9d8-7534cd6d8bc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_log_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_log_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8583940-cb64-47b5-bb59-2da94c3b803a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign_in_btn</value>
      <webElementGuid>e52b2d14-12e1-4e96-a626-37d0b69714ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>83e7bdf3-c01e-422f-b646-1f1716d3f9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d77b1507-6f67-4359-874a-2b4121b93157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>4c1a1478-276d-46fc-b91f-a18ce073aeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_log_in</value>
      <webElementGuid>28529fbd-aba4-4d0a-a1da-98a090629369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_log_in&quot;)</value>
      <webElementGuid>f1966f77-6c11-42b8-81d5-8884e3eeee83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_log_in']</value>
      <webElementGuid>3d8bc809-909f-4e9b-9eec-17e06aeff8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/div/div/div[2]/div[2]/form/input</value>
      <webElementGuid>4ac67bdb-628b-429d-94bf-6a1de43e9cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>93a3f731-fcc7-4af5-ab12-72e4098c3a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @type = 'submit' and @id = 'btn_log_in']</value>
      <webElementGuid>22be3aaf-94cc-4043-a424-96efe414afc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
