<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in with email_password</name>
   <tag></tag>
   <elementGuidId>73eb2360-327d-4bc2-a207-bb061d352fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-password-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-password-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e8c5ebf-4480-47e0-a91d-8535e0272c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1e5cd4c2-ca46-457f-928d-21528a6beb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>11426960-5a88-4fbc-b5fc-6de3a5837e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_field password_field</value>
      <webElementGuid>c7d7ce23-e540-4dc6-afb8-b677e1bc05ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>64038b27-1b74-4f20-b64f-78827552066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ea94842b-f94d-461d-975b-81fda237b29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-password-email</value>
      <webElementGuid>5e15c541-d723-4d86-8c97-b3636d1019da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>338403af-e3cb-4392-920e-400ae407b4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-password-email&quot;)</value>
      <webElementGuid>1fff55c4-ba18-4082-a43e-7c695bbe53e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-password-email']</value>
      <webElementGuid>96e6fc75-bf2f-4fa6-a134-b514b304f7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/div/div/div[2]/div[2]/form/div[2]/input</value>
      <webElementGuid>b38ccf0f-e68f-4e04-b4ca-2f0b805a82d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dd7a9c47-9617-41cf-b47e-ca947e597b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password' and @placeholder = 'Password' and @id = 'login-password-email']</value>
      <webElementGuid>4e3cba87-0ece-4fe6-a9f4-71b8d6064334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
