<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in with email_username</name>
   <tag></tag>
   <elementGuidId>4685bd92-58d8-4175-acb4-4a9c6ea595c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d83f2d7c-02a9-4a89-9e91-e9c89750ae63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>1ff3d27a-a591-4d54-a9fb-6eeb353414a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>70c3501b-5a5f-4a25-ab72-755b4ff76a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c0ad5f3-ff92-4559-a6a2-f2dcd06ef003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8f7921de-4b58-45ec-a85b-169841812a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@company.com</value>
      <webElementGuid>a9e8585c-110a-46d9-860f-ee8f4182afff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-content-wrapper&quot;)/div[@class=&quot;wrapSignIn login_screen&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;top_section&quot;]/div[@class=&quot;form_section&quot;]/div[@class=&quot;signin_method_section signin_email_section active&quot;]/form[@class=&quot;form_sign_up&quot;]/div[@class=&quot;input_div email_input&quot;]/input[@id=&quot;username&quot;]</value>
      <webElementGuid>8b2e3d73-17f8-43c7-805c-801ba233225e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username']</value>
      <webElementGuid>d722bef4-2a8c-4313-9359-8be60b9955f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/div/div/div[2]/div[2]/form/div/input</value>
      <webElementGuid>4de763eb-cf81-4264-8360-a1dc60d21c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>70cc2c66-cfcf-4348-b3d2-4ba6e7992a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'username' and @name = 'username' and @type = 'text' and @placeholder = 'name@company.com']</value>
      <webElementGuid>4b3b3052-f385-42fe-9d25-dd53abafde08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
